alias gar="git add -A"
alias gcm="git commit -m"
alias gcma="git commit --amend"
alias gcho="git checkout"
alias gcam="git commit -a -m"
alias gdel="git branch -D"
alias opush="git push origin master"
alias opull="git pull origin master"
alias hpush="git push heroku master"
alias h='heroku run'
alias hc="heroku run console"
alias hl="heroku logs"

alias gdf="git diff --name-status"
alias gl="git log --oneline"
alias grl="git reflog"
